promotion: false
toolbar_sticky: true
toolbar:
  - undo redo | blocks | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify bullist numlist | image link
plugins:
  - table
  - image
  - link
  - lists
  - media
  - autoresize
  - help
images_upload_url: '/uploader/image'

